spring:
  application:
    name: notification-service

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'

  mail:
    host: smtp.gmail.com
    port: 587
    username: malizorbaa.33@gmail.com
    password: mvdi xiov gmxz pobk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
